[package]
name = "battleships"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = { version = "0.26.2", features = ["derive"] }
rand = "0.9.0-alpha.1"
unicode-segmentation = "1.11.0"